from __future__ import annotations

import base64
from html import escape
from pathlib import Path
import random


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "assets" / "bear-mood-cycle.svg"
AVATAR = ROOT / "assets" / "avatar-bear.png"


# Edit moods here later:
# - Add a new dictionary to include another mood.
# - Change "message" to update the text shown in the widget.
# - Change "accent" to adjust the neon color for that mood.
# Keep text short so it fits inside the GitHub README image.
MOODS = [
    {
        "name": "Happy",
        "message": "All systems feel bright today.",
        "accent": "#39d353",
    },
    {
        "name": "Focused",
        "message": "Deep work mode is online.",
        "accent": "#58a6ff",
    },
    {
        "name": "Sleepy",
        "message": "Recharge first, then build.",
        "accent": "#a78bfa",
    },
    {
        "name": "Excited",
        "message": "A new idea just unlocked.",
        "accent": "#ffcc66",
    },
    {
        "name": "Love It",
        "message": "This build has extra heart.",
        "accent": "#ff7bba",
    },
    {
        "name": "Debugging",
        "message": "Tracing the bug with patience.",
        "accent": "#f97316",
    },
    {
        "name": "Tired",
        "message": "Low battery, still learning.",
        "accent": "#8b949e",
    },
]


def avatar_data_uri() -> str:
    encoded = base64.b64encode(AVATAR.read_bytes()).decode("ascii")
    return f"data:image/png;base64,{encoded}"


def render_svg(mood: dict[str, str]) -> str:
    name = escape(mood["name"])
    message = escape(mood["message"])
    accent = mood["accent"]
    avatar = avatar_data_uri()

    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 760 210" role="img" aria-labelledby="title desc">
  <title id="title">Daily refined bear mood widget: {name}</title>
  <desc id="desc">A GitHub profile bear mood widget using the real bear avatar and showing the current mood as {name}.</desc>
  <defs>
    <clipPath id="avatarClip">
      <circle cx="151" cy="105" r="66"/>
    </clipPath>
    <filter id="glow" x="-20%" y="-20%" width="140%" height="140%">
      <feGaussianBlur stdDeviation="3" result="blur"/>
      <feMerge>
        <feMergeNode in="blur"/>
        <feMergeNode in="SourceGraphic"/>
      </feMerge>
    </filter>
    <style>
      .panel{{fill:#0d1117;stroke:#30363d;stroke-width:2}}
      .screen{{fill:#010409;stroke:{accent};stroke-width:2}}
      .txt{{font-family:Consolas,Monaco,monospace;fill:#c9d1d9}}
      .muted{{fill:#8b949e}}
      .accent{{fill:{accent}}}
      .accent-stroke{{stroke:{accent}}}
      .stroke{{fill:none;stroke-linecap:round;stroke-linejoin:round;stroke-width:4}}
      .float{{animation:float 3s ease-in-out infinite}}
      .spark{{animation:spark 1.8s steps(1,end) infinite}}
      .cursor{{animation:cursor 1s steps(1,end) infinite}}
      @keyframes float{{0%,100%{{transform:translateY(0)}}50%{{transform:translateY(-4px)}}}}
      @keyframes spark{{0%,100%{{opacity:.28}}50%{{opacity:1}}}}
      @keyframes cursor{{0%,48%{{opacity:1}}49%,100%{{opacity:0}}}}
    </style>
  </defs>

  <rect x="8" y="8" width="744" height="194" rx="16" class="panel"/>
  <rect x="26" y="28" width="708" height="154" rx="12" class="screen" filter="url(#glow)"/>

  <g class="float">
    <circle cx="151" cy="105" r="76" fill="#010409" stroke="{accent}" stroke-width="2" filter="url(#glow)"/>
    <image href="{avatar}" x="85" y="39" width="132" height="132" clip-path="url(#avatarClip)" preserveAspectRatio="xMidYMid slice"/>
    <circle cx="151" cy="105" r="66" fill="none" stroke="#ffcc66" stroke-width="2" opacity=".78"/>
    <path d="M91 164c30 19 90 19 120 0" class="stroke accent-stroke" opacity=".42"/>
  </g>

  <g transform="translate(330 60)">
    <text class="txt muted" x="0" y="0" font-size="14">DAILY BEAR MOOD</text>
    <text class="txt" x="0" y="42" font-size="34" font-weight="700">{name}</text>
    <text class="txt muted" x="0" y="78" font-size="16">{message}</text>
    <text class="txt" x="0" y="118" font-size="15">&gt; generated by GitHub Actions<tspan class="cursor">_</tspan></text>
  </g>

  <rect class="accent spark" x="668" y="44" width="8" height="8"/>
  <rect class="accent spark" x="694" y="72" width="8" height="8"/>
  <rect class="accent spark" x="650" y="132" width="8" height="8"/>
  <path d="M54 170h150M216 170h24M574 170h88" class="stroke accent-stroke" opacity=".5"/>
</svg>
"""


def main() -> None:
    mood = random.SystemRandom().choice(MOODS)
    svg = render_svg(mood)
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)

    previous = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else None
    if previous == svg:
        print(f"Bear mood unchanged: {mood['name']}")
        return

    OUTPUT.write_text(svg, encoding="utf-8", newline="\n")
    print(f"Bear mood updated: {mood['name']}")


if __name__ == "__main__":
    main()
